import asyncio
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from playwright.async_api import async_playwright
from playwright_stealth import Stealth
import re


def extract_shop_id(torob_url: str) -> str | None:
    match = re.search(r"/shop/(\d+)", torob_url)
    return match.group(1) if match else None


async def get_shop_url(client: httpx.AsyncClient, shop_id) -> str | None:
    url = f"https://api.torob.com/v4/internet-shop/profile-website/redirect/?shop_id={shop_id}"

    try:
        response = await client.head(url)

        response.raise_for_status()

        return str(response.url)
    except httpx.HTTPError, httpx.RequestError:
        return None


async def run(base_url: str):
    # Load links directly from the HTML dump generated by Step 1
    try:
        with open("torob_dump.html", "r", encoding="utf-8") as f:
            html_content = f.read()
    except FileNotFoundError:
        print("torob_dump.html not found! Please run step 1 first.")
        return

    # Parse the HTML to extract the shop links
    soup = BeautifulSoup(html_content, "html.parser")
    items = soup.find_all("a", attrs={"data-testid": "shop-list-item"})
    pages = [item.get("href") for item in items if item.get("href")]

    print(f"Extracted {len(pages)} shop pages from HTML dump.")

    async with httpx.AsyncClient(follow_redirects=True, timeout=10.0) as client:
        browser = await p.firefox.launch(
            headless=False,
            ignore_default_args=["--enable-automation"],
        )
        context = await browser.new_context()
        page = await context.new_page()

        shops: list[str] = []
        tasks = []

        async def put_shop(sid):
            url = await get_shop_url(client, shop_id)
            if url:
                shops.append(url)

        for i, shop_page in enumerate(pages):
            print(f"Visiting shop {i + 1}/{len(pages)}")
            shop_id = extract_shop_id(shop_page)
            if shop_id:
                tasks.append(put_shop(shop_id))

        await asyncio.gather(*tasks)

        print(f"Successfully extracted {len(shops)} online shops out of {len(pages)}")

        # Save final URLs
        with open("shops.txt", mode="w", encoding="utf-8") as f:
            for shop in shops:
                print(shop, file=f)

        await browser.close()


if __name__ == "__main__":
    asyncio.run(run("https://torob.com"))
